"""Lua + Lua-data generator for the Hotel-v3 Resolve bundle.

The Resolve Scripts menu runs Lua reliably (``bmd`` is always injected).
JSON parsing in vanilla Lua is painful, so we ship the unified manifest
as both ``manifest.json`` (canonical artifact) and ``manifest.lua`` (a
sidecar Lua data file the importer ``dofile`` s at runtime).

The generated Lua does:

  1. Connect to Resolve via ``bmd.scriptapp("Resolve")``.
  2. Load ``manifest.lua`` from BUNDLE_DIR (hardcoded by the exporter,
     overridable via the ``STUDIOOS_AIEDIT_BUNDLE`` env var).
  3. Create a ``AI_Editor_<report_id>`` Media Pool subfolder with five
     children (source / commentary / visualizations / avatar / sfx) and
     ``mediaPool:ImportMedia`` each unique asset into the right one.
  4. ``mediaPool:CreateEmptyTimeline("AI_Editor_RoughCut_<report_id>")``,
     ``timeline:AddTrack`` until V1..V3 / A1..A4 exist.
  5. Walk ``manifest.tracks`` in V1..A4 order and ``mediaPool:AppendToTimeline``
     each clipInfo with explicit ``trackIndex`` + ``recordFrame``.
  6. Atmosphere clips on A3 with ``loop=true`` are tiled to fill
     ``tile_to_seconds`` (Runway's sound_effect cap is 30s; longer
     scenes need repeats).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List

# Track ordering used by both the manifest writer and the Lua importer.
TRACK_ORDER: tuple = ("V1", "V2", "V3", "A1", "A2", "A3", "A4")


def render_manifest_lua(manifest: Dict[str, Any]) -> str:
    """Render the unified manifest as a Lua data file.

    The Lua importer ``dofile`` s this and reads it as a regular table.
    Keys that collide with Lua keywords (``in``) use string-key syntax.
    """
    return "-- Generated by ai_editor.resolve_exporter — do not edit.\n" \
           "return " + _lua_value(manifest, indent=0) + "\n"


def render_importer_lua(*, bundle_dir_posix: str, report_id: str) -> str:
    """Render the Resolve Scripts-menu importer Lua.

    The bundle directory is baked in at generation time so the script is
    a self-contained, double-clickable Scripts-menu entry. The
    ``STUDIOOS_AIEDIT_BUNDLE`` env var overrides it for testing.
    """
    return _IMPORTER_LUA.format(
        bundle_dir=_lua_string(bundle_dir_posix),
        report_id=_lua_string(report_id),
    )


# --- Lua serialisation helpers -------------------------------------------

_LUA_RESERVED = {
    "and", "break", "do", "else", "elseif", "end", "false", "for",
    "function", "goto", "if", "in", "local", "nil", "not", "or", "repeat",
    "return", "then", "true", "until", "while",
}


def _lua_value(value: Any, *, indent: int) -> str:
    """Serialize a JSON-ish Python value as Lua source (table literals)."""
    pad = "  " * indent
    inner_pad = "  " * (indent + 1)
    if value is None:
        return "nil"
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, (int, float)):
        # Lua treats integers and floats the same in 5.1; render plainly.
        if isinstance(value, float) and (value != value or value in (float("inf"), float("-inf"))):
            return "0"
        return repr(value)
    if isinstance(value, str):
        return _lua_string(value)
    if isinstance(value, list):
        if not value:
            return "{}"
        parts = [f"{inner_pad}{_lua_value(v, indent=indent + 1)}" for v in value]
        return "{\n" + ",\n".join(parts) + "\n" + pad + "}"
    if isinstance(value, dict):
        if not value:
            return "{}"
        parts: List[str] = []
        for k, v in value.items():
            parts.append(f"{inner_pad}{_lua_key(k)} = {_lua_value(v, indent=indent + 1)}")
        return "{\n" + ",\n".join(parts) + "\n" + pad + "}"
    # Anything else — fall back to str().
    return _lua_string(str(value))


def _lua_key(key: str) -> str:
    """Render a dict key as a Lua table key.

    Plain identifiers use the bare-key syntax; keywords and anything
    with non-identifier characters use the ``["..."]`` form.
    """
    if (
        isinstance(key, str)
        and key.isidentifier()
        and key not in _LUA_RESERVED
    ):
        return key
    return f"[{_lua_string(str(key))}]"


def _lua_string(s: str) -> str:
    # Escape backslashes and double quotes; render embedded newlines as \n.
    escaped = (
        s.replace("\\", "\\\\")
         .replace("\"", "\\\"")
         .replace("\n", "\\n")
         .replace("\r", "\\r")
         .replace("\t", "\\t")
    )
    return f"\"{escaped}\""


# --- Importer Lua --------------------------------------------------------

# The braces inside the Lua body must be doubled ({{ }}) because we feed
# this through str.format with bundle_dir / report_id placeholders.
_IMPORTER_LUA = r"""--[[
StudioOS_Import_AIEdit
======================
Generated by Hotel-v3 (ai_editor.resolve_exporter).

Reads manifest.lua next to this script (or via STUDIOOS_AIEDIT_BUNDLE),
imports each asset into a Media Pool subfolder, creates the
"AI_Editor_RoughCut_<report_id>" timeline, and appends clips to
V1..V3 / A1..A4 with explicit recordFrame placement.

Run from: Workspace > Scripts > StudioOS_Import_AIEdit
After install: python R:/--CODE--/StudioOS-v1/scripts/install_resolve_scripts.py
]]

local BUNDLE_DIR = os.getenv("STUDIOOS_AIEDIT_BUNDLE")
if not BUNDLE_DIR or BUNDLE_DIR == "" then
    BUNDLE_DIR = {bundle_dir}
end

local REPORT_ID = {report_id}

print("==================================================")
print("StudioOS Import AIEdit — bundle: " .. BUNDLE_DIR)
print("==================================================")

local manifestPath = BUNDLE_DIR .. "/manifest.lua"
local ok, manifest = pcall(dofile, manifestPath)
if not ok or type(manifest) ~= "table" then
    print("ERROR: failed to load manifest at " .. manifestPath)
    print(tostring(manifest))
    return
end

local resolve = bmd.scriptapp("Resolve")
if not resolve then
    print("ERROR: could not connect to Resolve")
    return
end
local pm = resolve:GetProjectManager()
local project = pm and pm:GetCurrentProject() or nil
if not project then
    print("ERROR: no project open in Resolve")
    return
end
local mediaPool = project:GetMediaPool()
local rootFolder = mediaPool:GetRootFolder()
if not mediaPool or not rootFolder then
    print("ERROR: could not access Media Pool")
    return
end

-- Resolve project fps; the manifest's fps is a fallback.
local fps = tonumber(project:GetSetting("timelineFrameRate")) or manifest.fps or 25.0
print(string.format("Project: %s — fps: %.3f", project:GetName(), fps))

local function getOrCreateSubfolder(parent, name)
    local subs = parent:GetSubFolderList() or {{}}
    for _, f in ipairs(subs) do
        if f:GetName() == name then return f end
    end
    return mediaPool:AddSubFolder(parent, name)
end

local rootBundle = getOrCreateSubfolder(rootFolder, "AI_Editor_" .. REPORT_ID)
local subfolders = {{
    source         = getOrCreateSubfolder(rootBundle, "source"),
    commentary     = getOrCreateSubfolder(rootBundle, "commentary"),
    visualizations = getOrCreateSubfolder(rootBundle, "visualizations"),
    avatar         = getOrCreateSubfolder(rootBundle, "avatar"),
    sfx            = getOrCreateSubfolder(rootBundle, "sfx"),
}}

local function subfolderFor(relpath)
    if relpath:match("^source") then return subfolders.source end
    if relpath:match("^commentary") then return subfolders.commentary end
    if relpath:match("^visualizations[/\\]") then return subfolders.visualizations end
    if relpath:match("^avatar[/\\]") then return subfolders.avatar end
    if relpath:match("^sfx[/\\]") then return subfolders.sfx end
    return rootBundle
end

local imported = {{}}  -- relpath -> MediaPoolItem

local function importInto(relpath)
    if imported[relpath] then return imported[relpath] end
    local target = subfolderFor(relpath)
    mediaPool:SetCurrentFolder(target)
    local absPath = BUNDLE_DIR .. "/" .. relpath
    local items = mediaPool:ImportMedia({{absPath}})
    if not items or #items == 0 then
        print("  ! ImportMedia returned no items for " .. absPath)
        return nil
    end
    imported[relpath] = items[1]
    return items[1]
end

-- 1) Pre-import every unique asset path referenced anywhere.
local trackOrder = {{ "V1", "V2", "V3", "A1", "A2", "A3", "A4" }}
local seen = {{}}
local importCount = 0
for _, trackName in ipairs(trackOrder) do
    local entries = manifest.tracks and manifest.tracks[trackName] or {{}}
    for _, entry in ipairs(entries) do
        if entry.path and not seen[entry.path] then
            seen[entry.path] = true
            if importInto(entry.path) then
                importCount = importCount + 1
            end
        end
    end
end
print(string.format("Imported %d unique asset(s).", importCount))

-- 2) Create timeline.
local timelineName = "AI_Editor_RoughCut_" .. REPORT_ID
local timeline = mediaPool:CreateEmptyTimeline(timelineName)
if not timeline then
    print("ERROR: Failed to create timeline " .. timelineName)
    return
end
print("Timeline: " .. timelineName)

-- 3) Ensure track counts (default = 1V/1A; we need 3V / 4A).
local function ensureTrackCount(trackType, target)
    local cur = timeline:GetTrackCount(trackType) or 1
    while cur < target do
        if not timeline:AddTrack(trackType) then
            print("  ! AddTrack failed for " .. trackType .. " (have " .. cur .. ")")
            return
        end
        cur = cur + 1
    end
end
ensureTrackCount("video", 3)
ensureTrackCount("audio", 4)

-- 4) Track-name -> (mediaType, trackIndex) for AppendToTimeline.
local TRACK_INFO = {{
    V1 = {{ mediaType = 1, trackIndex = 1 }},
    V2 = {{ mediaType = 1, trackIndex = 2 }},
    V3 = {{ mediaType = 1, trackIndex = 3 }},
    A1 = {{ mediaType = 2, trackIndex = 1 }},
    A2 = {{ mediaType = 2, trackIndex = 2 }},
    A3 = {{ mediaType = 2, trackIndex = 3 }},
    A4 = {{ mediaType = 2, trackIndex = 4 }},
}}

local function makeClipInfo(mpi, trackName, inSec, outSec, recordSec)
    local startFrame = math.floor((inSec or 0) * fps + 0.5)
    local endFrame   = math.floor((outSec or 0) * fps + 0.5)
    if endFrame <= startFrame then endFrame = startFrame + 1 end
    local recordFrame = math.floor((recordSec or 0) * fps + 0.5)
    local info = TRACK_INFO[trackName]
    return {{
        mediaPoolItem = mpi,
        startFrame    = startFrame,
        endFrame      = endFrame,
        mediaType     = info.mediaType,
        trackIndex    = info.trackIndex,
        recordFrame   = recordFrame,
    }}
end

local function appendOne(mpi, trackName, inSec, outSec, recordSec, label)
    local clipInfo = makeClipInfo(mpi, trackName, inSec, outSec, recordSec)
    local result = mediaPool:AppendToTimeline({{ clipInfo }})
    if not result or #result == 0 then
        print(string.format("  ! Append failed: %s @ %.2fs (%s)",
            tostring(label or "?"), recordSec or 0, trackName))
        return false
    end
    return true
end

-- 5) Walk tracks in order and append.
local appended = 0
local skipped = 0
for _, trackName in ipairs(trackOrder) do
    local entries = manifest.tracks and manifest.tracks[trackName] or {{}}
    for _, entry in ipairs(entries) do
        local mpi = imported[entry.path]
        if not mpi then
            print("  ! Missing import for " .. tostring(entry.path))
            skipped = skipped + 1
        else
            local inSec = entry["in"] or 0
            local outSec
            if entry["out"] ~= nil then
                outSec = entry["out"]
            elseif entry.duration ~= nil then
                outSec = inSec + entry.duration
            else
                outSec = inSec + 1.0
            end
            local timelineIn = entry.timeline_in or 0

            -- A3 atmosphere tiling: repeat the rendered clip until the
            -- in-scene tile_to_seconds target is reached.
            if trackName == "A3" and entry.loop and entry.tile_to_seconds and entry.duration then
                local clipDur = entry.duration
                local target  = entry.tile_to_seconds
                local i = 0
                while i * clipDur < target - 0.001 do
                    local thisStart = timelineIn + i * clipDur
                    local thisDur   = math.min(clipDur, target - i * clipDur)
                    if appendOne(mpi, trackName, 0, thisDur, thisStart, entry.label) then
                        appended = appended + 1
                    else
                        skipped = skipped + 1
                    end
                    i = i + 1
                end
            else
                if appendOne(mpi, trackName, inSec, outSec, timelineIn, entry.label) then
                    appended = appended + 1
                else
                    skipped = skipped + 1
                end
            end
        end
    end
end

print("==================================================")
print(string.format("Done. Appended %d clip(s), skipped %d.", appended, skipped))
print("Timeline: " .. timelineName)
print("==================================================")
"""
